# Tomcat Server
server:
  port: 8080

# Logger
logging.level:
  web: DEBUG
  '[org.comit.project]': DEBUG
  '[org.hibernate.type]': INFO
  
spring:
# Active Profile
  profiles.active: default

# Banner Text
  banner:
    charset: UTF-8
    location: classpath:/banner/comit.txt

# Jackson Settings
  jackson:
    time-zone: America/Toronto
    date-format: yyyy-MM-dd
      
# Common Database Settings
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
         
---
    
# Default Profile
spring:
  config:
    activate.on-profile: default 

# Database Settings
  datasource:
    url: jdbc:mysql://localhost:3306/triangledb
    username: root
    password: admin123!
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate.ddl-auto: validate
    hibernate:       
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    
  h2:
    console:
      enabled: false   
---

server:
  port: 8080
     
# Prod Profile
spring:
  config:
    activate.on-profile: prod  

# Database Settings
  datasource:
    url: jdbc:mysql://localhost:3306/triangledb
    username: root
    password: admin123!
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate.ddl-auto: validate
    hibernate:       
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: false      
---

# Test Profile
spring:
  config:
    activate.on-profile: test  

# Database Settings
  sql.init:
    mode: always
    data-locations: classpath:/scripts/data.sql
    continue-on-error: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa123#
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:       
      naming.physical-strategy: org.comit.project.triangle.config.test.ProfileNamingStrategy
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

